packages:
  - 'packages/*'
  - 'packages/infra/lib/lambda/*'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  nx: true
  sharp: true
  unrs-resolver: true
  '@nestjs/core': false
